### ISSUE TITLE
DK statistik

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/ShoppingOffer#26]
Generel byudvikling + udvikling i erhverv i byer

**Comment by Spiderixius** [comment]
**Detailsalget forsatte stigende trend i tredje kvartal** 
https://www.dst.dk/da/Statistik/nyt/NytHtml?cid=26115

**Julehandlens betydning for detailhandlen**
https://www.dst.dk/da/Statistik/Analyser/visanalyse?cid=27144

**Her kan vi hente flere forskellige tabeller/grafer**
http://www.statistikbanken.dk/statbank5a/selectvarval/define.asp?PLanguage=0&subword=tabsel&MainTable=DETA152&PXSId=211696&tablestyle=&ST=SD&buttons=0

**Comment by Spiderixius** [comment]
**Odense i tal**
https://www.odense.dk/om-kommunen/statistikker-og-regnskaber/odense-i-tal/odense-i-tal
