### ISSUE TITLE
Byfortættelse/Byplanb (Letbanen + "By og Plan)

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/ShoppingOffer#28]

**Comment by anna0207** [comment]
https://www.odense.dk/byens-udvikling/byudvikling-og-omdannelse/undersoegelse-af-byens-kommercielle-liv

Her kan både byudvikling rapporten downloades + tal og analyser

**Comment by anna0207** [comment]
https://www.odense.dk/politik/politikker-og-visioner/byudviklingsplaner/kommuneplan/detailhandel/analyse-af-detailhandel-i-odense

Analyse af detailhandlen fra 2010
