### ISSUE TITLE
Homescreen - Google maps layout + activity

### ISSUE THREAD

**Issue by Spiderixius** [SuneJepsen/ShoppingOffer#3]
Implement the Google maps layout (shown in the image below marked with red)

**The layout should contain the following**:
- The map should have pin points for fake stores 

**The activity should contain the following**:
- The map should place pin points on the map which are retrieved by calling a method from the facade

![image](https://user-images.githubusercontent.com/10165995/47604226-b2380c80-d9f6-11e8-86b9-041a59ac93b8.png)

**Comment by SuneJepsen** [comment]
I get the following error when I try to run build the project:

![image](https://user-images.githubusercontent.com/5344877/47746199-f725a280-dc85-11e8-8b4f-f60448b24866.png)

@Spiderixius can you verify

**Comment by SuneJepsen** [comment]
Now a got a step further to this error
![image](https://user-images.githubusercontent.com/5344877/47749081-a36a8780-dc8c-11e8-9a06-7c2436dd3de1.png)

**Comment by SuneJepsen** [comment]
After updating the project I get the following error 

![image](https://user-images.githubusercontent.com/5344877/47752081-cd737800-dc93-11e8-9762-c9b29f0e7aad.png)

**Comment by Spiderixius** [comment]
Hey @SuneJepsen regarding the build error, simply rebuild the project. @veena2410 had it too when she was first checking out the development branch and a rebuild fixed it. 
Also, is this error only in GooglMaps branch?
