### ISSUE TITLE
Reserve functionality on Detailed\MyCoupons Activity

### ISSUE THREAD

**Issue by veena2410** [SuneJepsen/ShoppingOffer#35]
Implement countdown, this is so we can use the deadline and current time to determine the remaining time.

Ideas:
- Use Thread.sleep like functionality to countdown, regardless of where you are in the app.
- Maybe there exists a "Timer" object to use

TODO:
- Reserve -> decrease stock + countdown start + create offer-code
- Reserve expire -> increase stock (back to normal) + countdown stop + remove from "MyCoupons"
- Buy reserved -> countdown stop + add "MyCoupons"

**Comment by anna0207** [comment]
Android Countdown https://developer.android.com/reference/android/os/CountDownTimer
